#!/usr/bin/python3
import sys

def rsa(file_path):
    """
    function rsa to search file to convert number and format n=p*q
    """
    try:
        with open(file_path) as file:
            for n in file:
                n = int(n)
                if n % 2 == 0:
                        print("{}={}*{}".format(n, n // 2, 2))
                        continue
                i = 3
                while i < n // 2:
                    if n % i == 0:
                        print("{}={}*{}".format(n, n // i, i))
                        break
                    i = i + 2
                if i == (n // 2) + 1:
                    print("{}={}*{}".format(n, n, 1))
    except (IndexError):
        pass

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script.py <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    rsa(file_path)
